field: e041f8b3-f49c-4609-8cc3-7c444b1342da # Prize Tracker 
fieldLayouts:
  046eec14-c5d5-4c84-aa34-30d893299e52:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a078ffa1-ce84-4aa2-9b13-2aab9b3f00ad # Step Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 352f1330-fe18-446c-a848-492b1bea17a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae846c32-62f4-44c6-b0d8-684b675fc667 # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e45e0d5-d331-49d1-9e37-04c22a32f9b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6376d01-50c9-4e5d-90b4-16f9db1371bc # Is Complete?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c10b079-80c4-4344-a80a-dcea440450a9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11d37c4d-7bf8-40ec-bcf7-040b88730c17
        userCondition: null
fields:
  a078ffa1-ce84-4aa2-9b13-2aab9b3f00ad: # Step Title
    columnSuffix: toupehcy
    contentColumnType: string(200)
    fieldGroup: null
    handle: stepTitle
    instructions: 'e.g. ''Shipped'' / ''Delivered'' / ''Come to London'' etc.'
    name: 'Step Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 50
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ae846c32-62f4-44c6-b0d8-684b675fc667: # Date
    columnSuffix: hutgyvyq
    contentColumnType: datetime
    fieldGroup: null
    handle: date
    instructions: 'When this step occurred. Only fill this out when it''s been completed. '
    name: Date
    searchable: false
    settings:
      max: null
      min: '2024-01-01T00:00:00+00:00'
      minuteIncrement: 30
      showDate: true
      showTime: false
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  c6376d01-50c9-4e5d-90b4-16f9db1371bc: # Is Complete?
    columnSuffix: jvmmeiex
    contentColumnType: boolean
    fieldGroup: null
    handle: isComplete
    instructions: null
    name: 'Is Complete?'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: trackerStep
name: 'Tracker Step'
sortOrder: 1
