fieldLayouts:
  2305b490-d4bb-4a77-96f4-6abb399c1972:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Prize Information'
            type: craft\fieldlayoutelements\Heading
            uid: bb317847-ef29-4878-b049-af53ee607270
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 61639519-d2b0-4151-8d75-bf8c08a465b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2261b778-e4d1-4087-aac1-8acbe3f50f00 # Prize Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00e845be-4a53-4aef-ad95-644136490674
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 221c47a4-801e-417f-b57c-2f52909aeaf9 # Prize Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 178cd377-8821-4092-978f-ca167f6a4c1b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fe7bff52-aedb-42a4-833b-c79a6d6e7399 # Event Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89f57ec2-b1e9-4817-a5ca-0776989613bf
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b6099b58-2dbe-43c7-b952-a54919a29d9c # Terms and Conditions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a1955a5-c210-4bf2-a214-85471d2972c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Winner Information'
            type: craft\fieldlayoutelements\Heading
            uid: 79fa7e13-a3fd-48b3-90d5-4f13d2bda0f0
            userCondition: null
          -
            elementCondition: null
            fieldUid: eb9e36d1-d10c-47ae-ae91-a9ad7160c239 # Winner Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d3f798b-6c36-404d-9aa5-e45b34a1fb3e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 08370149-1cfc-4fc2-b81b-daec30eee227 # Winning Date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6488ff77-42ea-49b5-80f5-749a1db531b6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0c9c28ce-340e-4fb9-bf35-f198021e168b # Winner Phone Number
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bd491e9-f417-494a-b865-a90f84d1dd9c
            userCondition: null
            warning: null
            width: 100
        name: 'Prize & Winner'
        uid: 3339c809-4fe4-438f-b6d7-0724310f0a00
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Prize Status'
            type: craft\fieldlayoutelements\Heading
            uid: d6933ac5-d43f-4a87-ab53-91837b95bb00
            userCondition: null
          -
            elementCondition: null
            fieldUid: 091b6b83-dffb-4fa7-b468-cd9256d0cbce # Has Shipped?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e284a259-cfcc-4ccd-ac3a-776436d19c33
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 091b6b83-dffb-4fa7-b468-cd9256d0cbce # Has Shipped?
                  uid: 0d9de1fb-5cdd-40a7-85aa-c7fcd1a3cff0
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: eb29637f-799f-41e5-b0f7-5f6b898fe22e # Shipped Date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0885edbb-82f1-4319-a6e9-ce1d15826038
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 091b6b83-dffb-4fa7-b468-cd9256d0cbce # Has Shipped?
                  uid: d6f1fa2b-7a2c-473b-9b6b-02f77cdb125a
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: b23cb0e6-d07c-4e59-a79b-87960cc55ee3 # Tracking URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bf8716b-5d63-44e6-9f59-1a6f42c65063
            userCondition: null
            warning: null
            width: 50
        name: 'Prize Status'
        uid: aca43f5a-d6d6-45cf-a28b-b23c947768f8
        userCondition: null
handle: eventTickets
hasTitleField: true
name: 'Event Tickets'
section: 87c5a3f1-6b0c-4c20-bfc1-6d41949564c6 # Prizes
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
