fieldLayouts:
  79012184-8889-4ba2-ae26-ebe0869bd3a2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2be849af-8e09-47fc-82cf-e41ddfb50753
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ec89d16-d084-4ec7-b95d-a4cb3d88cfc6
        userCondition: null
handle: giftCard
hasTitleField: true
name: 'Gift Card'
section: 87c5a3f1-6b0c-4c20-bfc1-6d41949564c6 # Prizes
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
