fieldLayouts:
  a1e93583-f354-4a9b-ad16-76eb7ea4a27f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: edbb912c-792d-40c0-9ae5-abaf4e41940d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f353f522-b578-4bee-a55c-148aa03fff05
        userCondition: null
handle: meetAndGreet
hasTitleField: true
name: 'Meet and Greet'
section: 87c5a3f1-6b0c-4c20-bfc1-6d41949564c6 # Prizes
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
